### ISSUE TITLE
peerAddHandler is not working

### ISSUE THREAD

**Issue by pontiyaraja** [ipfs/ipfs-cluster#1102]
**Additional information:**
 - OS: ubuntu 18.04
 - IPFS Cluster version: v0.12.0
 - Installation method: binary

**Describe the bug:**

I'm trying to addd peers to the ipfs-cluster by using peerAddHandler but its failing to add peers

@hsanjuan @kishansagathiya @ZenGround0

**Comment by hsanjuan** [comment]
Please do not tag people in the issues. This does not help getting an answer more quickly.

---

Usually the peer add endpoint is the wrong endpoint to use. In order to add peers to a cluster they need to "bootstrap" to an existing peer it during start up. How this works for crdt or raft is documented here: https://cluster.ipfs.io/documentation/deployment/bootstrap/ .

The POST /peers endpoint might work to make a CRDT-mode peer open a connection to another peer, but I recommend not using this workflow and sticking to the documented procedures.

Regarding the specific failure with that endpoint, without logs, or error messages is very hard to even guess what can be wrong.

**Comment by pontiyaraja** [comment]
@hsanjuan 
```
why there is no clear documentation for ipfs-cluster.  
why there is no option to add peers by an endpoint 
why the code is written like one time configuration in ipfs-cluster
```

**Comment by hsanjuan** [comment]
There is lots of clear detailed documentation on the website.

The endpoint is not documented because it makes people do wrong things and using it without understanding can bring Raft clusters to errors that are hard to deal with.

I don't understand the third question, but this seems clearly off topic and I don't like the tone. There is very little I can do to help without information about the errors or how things don't work for you. If you provide that information, maybe I can help further?

**Comment by pontiyaraja** [comment]
> There is lots of clear detailed documentation on the website.
> 
> The endpoint is not documented because it makes people do wrong things and using it without understanding can bring Raft clusters to errors that are hard to deal with.
> 
> I don't understand the third question, but this seems clearly off topic and I don't like the tone. There is very little I can do to help without information about the errors or how things don't work for you. If you provide that information, maybe I can help further?

@hsanjuan why there is no api to add peers in ipfs-cluster, why ipfs-cluster written like one time bootstrap peer addition configuration. 

I can understand you are creating cluster by adding peer in DHT and the Raft, but why ipfs-cluster is still not optimised to do it dynamically. Why I required a restart of my ipfs-cluster.

**Comment by hsanjuan** [comment]
No cluster restart is required, you are supposed to bootstrap peers to an existing cluster on boot. If you have booted a peer that belongs to no cluster at all that peer is no use, so better simply let it join the cluster directly on boot.

Other than that, there's no evidence here that the peerAddHandler is not doing what it should do and using it is not the sanctioned method of doing things anyway, so I'll close this one.

**Comment by pontiyaraja** [comment]
> No cluster restart is required, you are supposed to bootstrap peers to an existing cluster on boot. If you have booted a peer that belongs to no cluster at all that peer is no use, so better simply let it join the cluster directly on boot.
> 
> Other than that, there's no evidence here that the peerAddHandler is not doing what it should do and using it is not the sanctioned method of doing things anyway, so I'll close this one.

**_`@hsanjuan I'm asking why you guys are not able to code like adding peers dynamically to a cluster without restarting the cluster-service`_**
