### ISSUE TITLE
Cluster consistently fails to propogate pins to newly added peers

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#112]
This issue was first found when running test 0015-add_pin_rm_peers.yml.  For concreteness I will discuss results with 4 peers and 3 files pinned, though the problem occurs for all peer and file-pin-numbers seen so far.  This test begins by removing two peers from the cluster.  It then pins 3 files to the cluster.  Finally it restarts the cluster daemon in the two removed peers and adds them back to the cluster with newly generated peer ids.  

The expectation is that after being added back the two new peers will replicate all 3 files (rep factor is default -1).  Consistently one peer will not pin all files.  In the instance of the failure I am currently documenting the first peer to depart and re-enter the cluster only replicates one of the three expected pinned files by the end of the test.  As I recall the peer erroneously not replicating is usually the first node of the departing group (and so the first to depart and reenter) though I believe this is not always the case.  Also to my recollection it is usually only one or two pins that the erroring peer fails to replicate, I believe in all instances of the failure the peer replicates at least one pin correctly.

In the past I have seen the erroring peer display incorrect information about the status of the other departing peer, saying that this peer also does not replicate the pins, though in the current failure that I am documenting this is not the case: here all peers agree that 1 pin is replicated everywhere and that 2 pins are only replicated in 3 nodes.  This does not appear to be a timeout issue.  In this failure instance I query cluster status 15 minutes after launching the test and the failure to replicate is still present.

Looking through the logs one thing to note is that in the departing peer that successfully pinned all 3 files, there are three lines of the form `issuing pin call for <cid>`, whereas in the departing peer that only pins 1 file there is only one line of this form.  It seems that this peer is not being informed of all the pins it should be replicating upon reentry.  Right before the pins are issued in the log of the peer in error, there are a few raft warnings that aren't present in the correctly replicating peer that reenters the cluster.  These warnings are:
`[WARN] raft: Failed to get previous log: 14 log not found (last: 11) raft.go:45`
`[WARN] raft: Previous log term mis-match: ours: 3 remote: 1 raft.go:45`
`[WARN] raft: Previous log term mis-match: ours: 2 remote: 1 raft.go:45`
`[WARN] raft: Clearing log suffix from 10 to 11 raft.go:45`

**Comment by hsanjuan** [comment]
I'll look at this. First thoughts: 4 peers is a bad testing number and leader election might cause problems if two peers leave. Term mis-match issues might come from a split-head scenario (two or more leaders commiting stuff to the logs which are then later joined).

Need to try to reproduce myself.

**Comment by ZenGround0** [comment]
I have more data concerning this failure.  In the following table vertical columns represent the total number of nodes in the cluster before 1 node is removed and the horizontal columns determine how many pins are made in the cluster after 1 node is removed.  I narrowed the problem scope down to 1 peer leaving because it became clear that failures are universal in this scenario and it made sense to focus on understanding simpler failures first.  There is an independent failure mode (X) that I have only recorded in clusters of size 2 where the peers don't even recognize that they are in the same cluster after adding.   Unrecorded trials are left blank.  In the cases I saw something unexpected I recorded again and always got 2 again and separated the two values with ||.

                                  Total Nodes
               2            3            4            5            6           
--------------------------------------------------------------
      1   |  X             1                           1            1
p         |
i     2   |                  2                                         2
n         |
s    3   |  X              2            2             2            2
           |
      4   |                  2            2                           2
           |
      5   |  X             2            (5||2)        (1||2)       2
      .    |
      .    |
      .    |
     10  |                                                 2


This establishes that 2 failing pins and then the rest going through on the removed node is very common but that this is based on a race somewhere.  Also this problem is unrelated to the spurious case of 2/4 removed, but happens whenever a peer is added into a cluster with existing pins.

**Comment by ZenGround0** [comment]
Two possible explanations I am still exploring
1. The consensus log is not being updated for the joining peer for up to 2 (usually) pins so it never has a chance to track them
2. The pin tracker incorrectly registers up to 2 (usually) pins as been remotely tracked.

**Comment by hsanjuan** [comment]
Link to test in question: https://github.com/ipfs/kubernetes-ipfs/blob/master/ipfs-cluster/tests/0015-add_pin_rm_peers.yml

Thoughts:

**Is there a chance that, after re-adding the peers, you are not waiting enough before checking if they are pinning all the things they should be pinning?**

When a cluster node starts, and consensus state is correctly synced up to other nodes, a StateSync operation is triggered. This translates the Raft state to the PinTracker to make sure things in the Raft state are tracked and pinned (depending how raft sends the new state, it may not replay every operation in the log and thus the pin tracker gets not notified of the latest state).

StateSync() is then run reguarly, by default every minute (following configuration value):

        DefaultStateSyncSeconds          = 60

It *seems* the test:

* Restarts departed peers somehow (are they on standalone mode then?)
* Adds them to an existing cluster
* Immediately checks ipfs-cluster-ctl status on some pins

`status` checks the local state. But the local state may not reflect the "shared state" (ipfs pin ls) because no StateSync() has run yet in the newly-added peers. In order to test this theory you can:

* Reduce the `state_sync_seconds` configuration option to something smaller on the peers
* Wait and see
* Check that the pins are part of `ipfs-cluster-ctl pin ls` rather than `ipfs-cluster-ctl pin status` (that tells you if the re-joined nodes see the right shared state at least and the problem is with the local state, or if they really missed the common shared state).

**For your explanation number 2: If the cluster is in "pin all" mode (replication factor -1), the pin tracker should never register pins as "remotely tracked"**, so unlikely this happens (If I'm correct).

---

**There might be a problem with the shared state**

**PLEASE CHECK THE OTHER THEORY BEFORE GOING DOWN THIS RABBIT HOLE**. Looong explanation below.

After doing `peer rm`, the peer should shutdown after a second or so. 

Because it was removed and the peer itself knows, it will empty the list of known peers right before shutting down (https://github.com/ipfs/ipfs-cluster/blob/master/peer_manager.go#L69).

The Shutdown() method will save the empty list of peers to the configuration (https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L439).

When the peer it's restarted, it does with an empty set of peers. Thus it goes into single-peer mode and elects himself as leader, but re-using all the raft data that it had before.

When the peer is added to the main cluster, while it has been running on single mode, Raft sees that there were two cluster who have been running with a leader and prints the `election term mismatch` which basically should invalidate one of the leaderships (this is purely an assumption on what's a reasonable expected behaviour here from `raft`).

This is a non-standard situation in raft nevertheless. You are merging two clusters (the main cluster and a single node cluster) which both had valid leaders. In any case, the lonely peer is added to the main cluster. It receives the new list of peers and updates the Raft internal state to that (because it's its own leader). The main cluster does the same. Suddenly the single-peer and the main-cluster have the same list of peers. Either two of them claim to be leaders and an election is triggered or the lonely cluster steps down because there's new someone else with greater terms. Somehow, in the end a single leader results and all peers in the cluster know all other peers.

If you are suddenly not adding 1 single peer, but 2 or 3 at the same time, I could imagine things might go wrong at some point. (more on this later).

Anyways, once there is a leader, everyone needs to make sure they're up to date on the Raft log. So they look at their last log entry. The newly joined member should realize that its raft log is behind (it did not pin anything). If the states had diverged, you would have a problem. Luckily it's not fully the case because the state user-data is just older on the new member.

So it needs to get the last state of the log. Raft can do this by replaying the log (sending 1 update per log entry) until the new peer is up-to-date, or by sending a full snapshot if the state. If I remember well, Raft will only send a full snapshot when there are a lot of log entries to be replayed.

If the log is replayed, it should end up calling Apply() (https://github.com/libp2p/go-libp2p-raft/blob/master/fsm.go#L35) which should end up calling our ApplyTo() (https://github.com/ipfs/ipfs-cluster/blob/master/consensus/raft/log_op.go#L39) which should end up notifying the PinTracker with the new pins (LogOpPin). **The problem is, I'm not 100% sure this happens on a raft-state-catch-up situation (I would expect it to, but I'm not sure)**. And if it happens, I'm not 100% sure it's fail proof when a bunch of single-peer nodes are re-added to the cluster.

**Note**: The internal Raft shared state keeps the user-data (our log entries) AND also the list of raft peers. That means, when adding a single-cluster peer to an existing cluster, even if the user-data has not diverged, the Raft log has definitely diverged because any change in the raft peers is a log entry internally in `raft`. I am not sure how well this is handled but could be a source of problems too.

---

I hope this clarifies a bit (or maybe confuses you a lot more). This is probably the most complicated part and uncovering bad behaviors is why this test should exist. That said:

* We know peer bootstrapping works relatively well. A bootstrapping peer does not have the chance to run as single-cluster so maybe if nothing else works it's worth trying to re-add the peers by bootstrapping them direclty (and not peer-adding).
* Much of my comments on expected behavior are because that is how I have seen things working on other tests and when manually testing (so I think raft strives to work like that at least).
* When re-adding the peers (regardless of whether they picked up the new pins or not), we should really make sure that there are no [raft] errors in the logs. Maybe ipfs-cluster reports all peers have the right peers, but the internal raft state is somehow not right and that's why the shared state is not coming (if that turns out to be the problem).
* The worse situation here is that everything checks, there are no raft errors after re-adding the peers, you can keep pinning things and those works for everyone, and that only some log entries while the peers were gone have been lost. If that's the case, we need to come back and study more closely why this happens. I'm hoping it's something else though.

**Comment by hsanjuan** [comment]
oh and I forgot to add that all the peerAdd/Rm `raft` logic changed in their `v2` branch (probably because it did not work too well with dynamic set of peers), so it might even be a raft misbehaviour in the end even if we do everything right.

**Comment by hsanjuan** [comment]
@ZenGround0 do I remember right that we came up with a fix for this? Did we merge it? It had to do with using a clean raft state when re-adding peers right ?

**Comment by ZenGround0** [comment]
@hsanjuan, yes thanks for checking in.  I got distracted preparing for lab week and only got around to implementing the fix this weekend.  I am blocked on submitting the PR by the peers add libp2p-related failure, as I have been unable to run any tests to make sure the fix works as expected.

**Comment by ZenGround0** [comment]
PR 170 addresses this issue by saving peers to bootstrap by default when saving.  Note that this discussion will stay relevant as we continue to iron out useability issues arising from inconsistent raft state.
