### ISSUE TITLE
health metrics freespace shows configuret freespace and not actual freespace

### ISSUE THREAD

**Issue by i5heu** [ipfs/ipfs-cluster#1123]
```
ipfs@ipfs-cluster-master:~/ipfs-cluster-ctl$ ./ipfs-cluster-ctl health metrics freespace
XXXX | freespace: 1000 GB | Expires in: 21 seconds from now
```

**Additional information:**
 - IPFS Cluster version: 0.12.1

**Describe the bug:**
My machine has only 20GB left, but freespace shows 1000GB free.
This is because 1000GB is configured (StorageMax) in IPFS, but the actual freespace (e.g. linux command df) is not considered. 

https://github.com/glvd/cluster/blob/d0d3ea64c1d0994765d48d5efe4195c051bdd728/informer/disk/disk.go#L99-L104

**Comment by i5heu** [comment]
https://stackoverflow.com/questions/20108520/get-amount-of-free-disk-space-using-go

**Comment by hsanjuan** [comment]
Hello,

we are not using actual disk space because it has too many pitfalls:

* Need to figure out on what storage medium is the IPFS repository storing things
* Does not work if the IPFS daemon is not running locally
* Does not work if the IPFS daemon is running locally but with a remote datastore that needs some sort of authentication (S3)
* Does not help if the user does not want to dedicate the full hard drive to IPFS things
* Introduces additional complexities in code.

Therefore, using StorageMax is more convenient and provides a very clear way for users to indicate their available storage.

**Comment by i5heu** [comment]
thanks to make this clear!

**Comment by frankTheTank72** [comment]
Hi all , 
was searching for the same question and understood the problems of seeting StorageMax in an automated way. But still I think we can optimize this ...

My idea :

A user starts cluster-follower with a new attribute -ClusterStorageMax XXGB
In this case we add a new tag in the IPFS config with ClusterStorageMax = xxGB
Now within the cluster-follower app we check in a given interval or on a trigger  the size of the repo and calculate = StorageMax = Max(0, ClusterStorageMax- RepoSize)
StorageMax will be updated on the IPFS config.

If we introdcue this we would have a more clear picture on cluster how much space is left on each cluster node. S(till we would have the poblem if some put a fake value in, but in general it is more accurate.)

From my point fo view it also helps a  cluster with set values for min and max replication to select the correct node list.

Happy to hear your feedback....

**Comment by RubenKelevra** [comment]
@frankTheTank72 this is completely unrelated to the initial ticket. Please use a dedicated ticket for your feature request.
