### ISSUE TITLE
Support `local=true` as a configurable option for the proxy endpoints (:9095)

### ISSUE THREAD

**Issue by rryter** [ipfs/ipfs-cluster#1292]
Hello 😄 

As per [discussion](https://discuss.ipfs.io/t/kubernetes-best-practices-in-regards-to-ipfs-cluster/9834), the rest api /add endpoint (:9094) supports the setting `local=true`. 

> This will just add on the node receiving the request (and not all nodes at the same time), and cluster-pin when finished. The rest of the nodes will copy the content via pubsub, much faster.

We would like to run a public IPFS-Cluster and therefore plan to allow users to use the IPFS-Proxy API (:9095). 

It would be awesome if the setting "local=true" would be a configurable option.
I assume the default would be `local=false` but we could set it to `true` for our cluster.

Does that make sense? 

I'm new to IPFS / IPFS-Cluster so I don't know if this would be applicable to other enpoints too?

👋

**Comment by sergeiudris** [comment]
hi and peace to the cluster) I'll take this issue, want to start contributing, as the `good first issue`, to see what's what

**Comment by hsanjuan** [comment]
hi @sergeiudris , go ahead! thanks!

**Comment by sergeiudris** [comment]
- as of current version (v0.13.1), both restapi and ipfsproxy already support `local=true`
- both call `AddMultipartHTTPHandler`, which leads to `AddAllAndPin` and `PinRoot` 
- when `local=true`, `dag_service/Add` creates BlockAdder with empty dests ( []peer.ID{""} ), so `PinRoot` becomes a no-op: last step -  `rpcClient.MultiCall "BlockPut"` - is called with empty destinations
- so when we call either restapi's or ipfsproxy's `/add` with `local=true` or `shard=false`, `"BlockPut"`s are not called
---
- test  for `local=true`? although it's not *what* but *how* - in both cases files are pinned
- there is for example `TestAPIAddFileEndpointLocal` in restapi but it tests that files are there rather then was adding blocking or not
- the test could be (is it needed?)
  - create N-node test cluster ( like in `ipfscluster_test`) 
  - disable (possible?) pubsub sync mechanism
  - make actual http requests `/add?local=true/false` within test func 
  - test: with blockPuts(`local=false`), files will be on every node even without pubsub, with `local=true` only one node (because pubsub disabled)
- issues with this test as of now
  - test `createClusters` starts restapi and ipfsproxy on random ports (which is great), but only restapi exports `HTTPAddresses` (to be able to get the host:port for http request `/add`), so `HTTPAddresses` would be needed in ipfsproxy as well
  - how to disable/enable pubsub in one of the clsuters returned from `createClusters` (haven't looked at it yet)

**Comment by hsanjuan** [comment]
oh, it's true... it's done already because the code path is the same.

> creates BlockAdder with empty dests ( []peer.ID{""} )

No, dests are not empty. It has 1 dest, which is `""`. This is the `local peer`. The BlockPut rpc calls get executed in the same peer (bypassing the rpc request/response - this is in go-libp2p-gorpc).

In the end adding "locally" is the equivalent of adding with 1 destination. I think the codepaths there are hopefully well-tested (and tried).

Thanks a lot for looking into this, though. Probably best to spend time on some of the other open issues. I'm very sorry that I did not realize this was there already.
