### ISSUE TITLE
Added pins stay on PIN_QUEUED even when IPFS nodes are able to find the content

### ISSUE THREAD

**Issue by dholms** [ipfs/ipfs-cluster#1312]
**Additional information:**
 - OS: NixOS 20.03
 - IPFS Cluster version: 0.11.0
 - Installation method: dist.ipfs.io
 
**Describe the bug:**
We have a cluster of 5 nodes running. It was healthy for about a week but now when pins are added, the status for all 5 nodes remains as `PIN_QUEUED` and the IPFS nodes do not fetch the requested content.

I've verified that ipfs _does_ have access to the content, as `ipfs cat {cid}` and `ipfs pin add {cid}` both work. Even after doing so,  reattempting the cluster pin does not work.

I've also verified that our setup in staging (of 3 nodes) is healthy and works as expected.

Some context on our setup:
We are running 5 nodes in 5 separate EC2 instances. 3 are in us-east-1 and 2 are in eu-north-1. Nodes within the same region use the same s3 data store from `/blocks`, but `/` is kept on disk. The cluster currently has around 18000 cids pinned (which amounts to around 1TB of data)

**Comment by hsanjuan** [comment]
Pins would only stay in PIN_QUEUED state if there are already N pins in PINNING state (with N defined at `pin_tracker/stateless/concurrent_pins` in the configuration).

Can you double check? (`ipfs-cluster-ctl status --filter pinning`).

**Comment by dholms** [comment]
Thanks for the quick response.

I can confirm that our config has 10 concurrent_pins & there are 18 pins that are in various states of `pinning` across the cluster.

These seem like strange defaults for the cluster, especially with pinning being an async operation that does not timeout. Essentially if 10 bad CIDs are passed, our infrastructure stops working.

Is there a recommended solution for ensuring that this does not happen to our cluster again? 

My thought is:
- Raising the allowed number of concurrent pins
- adding an `expireAt` to the `POST /pins` request (we want to allow users to pin large files, so this would need to be a long time, but at least it wouldn't be for eternity

**Comment by dholms** [comment]
Is there somewhere that I can read the rationale/tradeoffs for limiting concurrent pins? I'm trying to gauge what we could raise that limit to without overwhelming the underlying IPFS nodes

**Comment by hsanjuan** [comment]
The `pin_timeout` value in the configuration is the time cluster waits for a block to arrive while pinning something.

Otherwise said, the `pin_timeout` value in the configuration specifies how much time needs to pass before an item that is PINNING goes into PIN_ERROR after the last block from the object that is being pinned was received by IPFS.

That means, pins will error only if no new blocks are received. An arbitrarily large object will stay pinning for as long as it needs, as long as new blocks are being received and it is not stuck. You need to adjust `pin_timeout` to whatever is acceptable for you, but it can be potentially a low value.

If IPFS is fetching 10 things in parallel, they may be more slow to fetch than if it's doing 2 at a time as well. So that matters too, but it depends on your setup and the usage you do.

Finally, pins in PIN_ERROR state will eventually be retried and go back to the pinning queue. This happens as defined by `pin_recover_interval`. By the time that happens, other objects that were queued before should have had the chance to pin, because they were first in the queue and will take the slots left by the pins that errored.

These configs options are documented here: https://cluster.ipfs.io/documentation/reference/configuration/

**Comment by dholms** [comment]
Got it. Thanks for the advice @hsanjuan!

I looked at config options while setting this up, but didn't realize the the interplay between these settings until it bit us.

You can close this issue, because it doesn't appear to be a bug in the code. But I might suggest that default config options are updated, or a call out is added in the documentation.

We're using ipfs-cluster in a fairly straightforward manner, and were surprised when our system stopped working a week in under relatively light load. If this is called out somewhere in the documentation and I missed it, my apologies!

**Comment by hsanjuan** [comment]
What do you recommend for default options? Pinning timeout is 2 minutes, pin concurrency is 10 right now.

**Comment by dholms** [comment]
Out of curiosity, was pinning timeout ever defaulting to longer? For some reason our cluster is set to 24hrs, and I'm pretty confident that we never manually changed that value. But something could have definitely gotten mixed up along the way.

2 minutes seems reasonable. I'd raise pin concurrency higher than 10. I know IPFS can handle a wantlist of larger than 10 CIDs. It's difficult for me to give a clear cut answer here. To be honest, I'm not sure the level at which you'd start seeing a serious hit to performance. We're thinking of experimenting with larger values (say 100) and seeing how IPFS handles it.

Is there any consideration that pins that are actively being downloaded and pins that are still in the content-discovery phase could be treated differently?

**Comment by hsanjuan** [comment]
>  For some reason our cluster is set to 24hrs, and I'm pretty confident that we never manually changed that value. But something could have definitely gotten mixed up along the way.

Yes, we changed it perhaps in the last release. #1160 

> Is there any consideration that pins that are actively being downloaded and pins that are still in the content-discovery phase could be treated differently?

I don't think so. I think 50 is an ok value for a production cluster. For an at-home cluster peer, 10 is probably nicer. It really depends. You need to test and find what works best given the number of pins you receive etc.

**Comment by dholms** [comment]
> Yes, we changed it perhaps in the last release

got it. This is a much better default, and we likely wouldn't have run into these issues if we'd had pine timeout set to 2 min :+1: 

> I don't think so. I think 50 is an ok value for a production cluster. For an at-home cluster peer, 10 is probably nicer. It really depends. You need to test and find what works best given the number of pins you receive etc.

50 with a 2 min timeout sounds fair. 

Thanks for your responses here. Very helpful!
