### ISSUE TITLE
Network connectivity needed for build

### ISSUE THREAD

**Issue by ledettwy** [ipfs/ipfs-cluster#143]
I noticed that the Makefile included for this is trying to download several things from the Internet.  This is not going to work for any build environments that don't have internet connectivity (like mine).  A Makefile should only contain instructions on how to build the source files it's included with.  They should not contain any instructions which require downloading something from the Internet.

**Comment by ledettwy** [comment]
Update: after looking through the build system a bit, I guess the network connectivity part is just a normal part of building a go program (to fetch the dependencies), but the fact that it's downloading ELFs and executing them is definitely nonstandard.

**Comment by hsanjuan** [comment]
Hi,

I sympathize with your comments. The makefile downloads `gx` and `gx-go` which are used to manage dependencies (gx fetches deps from ipfs). This is the same strategy as used by ipfs itself, so that is were it comes from. Note that the ipfs ecosystem is not using Makefiles in the most traditional way. They are rather a way to script the builds which provides a well-known interface to the user (`make build`/`make install`).

By downloading a specific version of gx, ipfs-cluster can bootstrap its own build in a very reproducible way.

If your build environment does not have internet conectivity, you will need to preload gx, gx-go and all the gx-downloaded-deps.

Let me know if I can be of any help there...
