### ISSUE TITLE
Main priorities for ipfs-cluster in the next months

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#163]
This is a bit shaky as cluster priorities and timelines are related to the ipfs-project ones. But I'm going to attempt to outline some objectives for the next cycle of cluster development:

* **1. Cluster is an stable, production-grade, ipfs-for-the-cloud distribution**: ipfs-cluster allows to coordinate multiple ipfs nodes by providing seamless replication of data. These nodes may be part of the same datacenter, or run in different clouds/regions. These nodes may be ipfs-clusters themselves.
* **2. Cluster facilitates the handling of big datasets**: storing big datasets on ipfs becomes easier with cluster. Cluster makes it easier to track, distribute and replicate big datasets among ipfs nodes.
* **3. Cluster users have a delightful experience**: Users approaching ipfs-cluster recieve prompt feedback and help from the team. User-requested features are considered and prioritized when possible. Documentation is maintained and expanded.

Once these are pinned down we will need to discuss key results. These objectives are very probably long lasting into more than a single quarter.

**Comment by ZenGround0** [comment]
I agree with the general outline.  Something not explicitly stated in the 3rd point that might be worth pointing out is that the tool itself should be extremely simple and pleasant to use.

Below are the sketches of a few key results I see being important even if objectives shift around a bit.  (WIP)

Understanding current performance -- this helps us know if we have made pinning large files easier, and if we have provided seamless replication of data.
We should have performance tests that record a set of metrics across different settings
For example the performance tests might include: time it takes to pin 10GB file, time it takes to rebalance content after a fault, and the settings might include: a local cluster residing in a single datacenter or aws region, a global cluster spread across nodes on 3 different continents, an ipfs-cluster whose nodes are themselves ipfs clusters.  --Note this implies setting up some infrastructure which is probably a key result of its own--

Some basic product work understanding what users want.  This way we can identify the pain points for users pinning large files that we are trying to make easier, or what is currently not seamless about data replication with cluster.
This could be as simple as compiling all user anecdotes from the issues or running through an intended use case ourselves and recording what goes wrong.   From what I gather from the issues, continued input from @ferranbt, @Vaelatern, @ccampbell and @segator regarding the problems they run into with cluster for their use cases will be very helpful for this.

After we measure performance and identify the usability bottlenecks, improving performance in these areas can become a key result.  From previous discussion adding erasure codes seems like a popular idea for improving performance in general and so perhaps this work can begin in parallel with measuring the problems.  Digressing a little from kr discussion, @hsanjuan it would be good to sit down and talk about your thoughts on chunking files and erasure coding (why, how, where in ipfs people should start looking to get examples, possible tradeoffs between performance and UX simplicity, understanding how cluster and ipfs are used together in a world where cluster stores data that must be somehow recombined across nodes before access).

**Comment by hsanjuan** [comment]
@ZenGround0 then maybe renaming objective 3 to:

* **3. Cluster is a delightful experience**: Cluster is simple and delightful to use. Users approaching ipfs-cluster recieve prompt feedback and help from the team. User-requested features are considered and prioritized when possible. Documentation is maintained and expanded.

Though I'm not super sure how to measure simplicity and delightfulness.

**Comment by hsanjuan** [comment]
Some key results for 1:

* At least 1 production cluster is run and maintained, used with real content.
* Gateways use ipfs-cluster. Pinbot integrates with it.
* A mutli-region cluster is set up for easy testing
* A list of composite cluster usecases exists
* Composite cluster usecases are supported
* Composite clusters are tested
* Kubernetes-ipfs-cluster tests run on a real kubernetes cluster

**Comment by hsanjuan** [comment]
Some key results for 2:

* There is an RFC and discussion about the approach needed to support things like large file chunking, tree balancing and erasure coding.
* Cluster supports chunking large files and pinning them among multiple peers
* Given a large tree, cluster supports pinning subsets of that tree in different peers
* Given a file, cluster supports erasure-coding-based storage of that file among multiple peers and later retrieval
* ipfs-pack and ipfs-cluster work together to pin datasets

**Comment by hsanjuan** [comment]
Some key results from 3:

* All open issues receive feedback from maintainers
* All bugs are assigned and work on them is scheduled
* Every working week, at least two commits address/improve documentation
* Cluster receives A+ in go-report and there are no issues
* Code-climate integration
* Tests run in jenkins rather than travis
* REST API is properly documented (swagger or so)
* Cluster use-cases brought up by are gathered in a document
* A product readme specifies which usecases cluster addresses (and which not)

**Comment by ZenGround0** [comment]
@hsanjuan Some thoughts leading into tomorrow.

Priorities:
To me the work listed above that has lowest priority involves implementing chunking and erasure coding files.  To work on this in good faith I want to know more about how cluster is being used / plans to be used and have a solid motivation as to why this will improve those cases.   For example right now it seems that most users are being slowed down by consensus issues or other lacking features rather than being burdened by storing too much data.  Granted, it is pretty obvious that storing less data and achieving the same replication is a good thing, so I agree that the RFC process should be started soon for chunking + FEC.  I am also thinking we should invest in understanding use cases better before implmenting because adding this functionality forces some design choices that will have effects on how ipfs-cluster is used.

I see among the highest priorities running cluster on the ipfs gateway, fixing bugs, responding quickly to open issues, and documenting use cases.  Next I see performance tests, the associated goals of deploying a real cluster with k8s and deploying a multi-region cluster, and documentation Fridays.  After this I see infrastructure improvements and composite cluster goals.

This is my shot at priorities, excited to get some feedback particularly where your priorities are conflicting

What I want to work on:
Ironically I am probably most interested in working on chunking and erasure coding :) 

I am very interested in fixing bugs and working on whatever features we decide are worth pursuing as one of my big goals this quarter is to become fluent with cluster's code.  I am also interested in doing a lot of work surrounding getting performance tests going, and in particular designing and running the experiments we will use to take down measurements.  Finally I would like to do a decent amount of infrastructure work (jenkins + code climate) so that I get to know the repository and its build / test environment better.

I would like to stay away from replacing the pin-bot on the gateway as it sounds like it would be higher pressure than my expertise would comfortably allow.

While this is my preference list note that I am very flexible and happy to do other things when more urgent

Making current krs more measurable WIP:
I left the hardest one for last.  A lot of these seem to be binary out of necessity.  Perhaps this is indicative of some aspect of cluster, perhaps its early stage?  We can talk more tomorrow but below is my best try at making krs in my priority list measurable.  I left some krs with ?? before the number when I didn't understand the task behind the result well enough to try to improve wording.

KRs for Obj 1:
1. All ipfs gateways migrate from pinbot to ipfs-cluster for storing 100% of files with 100% uptime
2. 1 to 3 primary usecases (including composite) for ipfs-cluster are specified, documented and approved by majority of community
3. Performance tests are designed across 3 key variables and results are recorded for local and multi-region clusters (example variables: number of peers, number of pins, size of files)
??4. Composite cluster tests 
??5. Composite cluster support

KRs for Obj 2:
1. RFC discussion surrounding chunking + FEC in ipfs-cluster is concluded and results in a clear design decision for how ipfs-cluster handles adds and gets.

KRs for Obj 3:
1. All reported bugs are examined, discussed, and assigned within x(3?) days of being reported  
2. All open issues receive feedback from maintainers within x(48?) hours
3. Every work week 2 or more commits improve documentation 
4. All potential use cases described in the issues by the community are added to a document.
5. Releases of binaries and docker images occur every month
6. Before Every release cluster receives A+ in go-report and there are no issues
7. Travis is completely deprecated and all tests run in Jenkins
??8. Code climate integration
??9. Rest api swagger doc

**Comment by hsanjuan** [comment]
We have OKRs (Objectives+Key Results) more or less ready, awaiting a final OK after the IPFS project freezes theirs.

**Comment by hsanjuan** [comment]
https://docs.google.com/spreadsheets/d/1rLxvRfdYohv-dhzVAo1xfeJOUa7uGfq6N_yyKw0iRw0/edit#gid=1162879508

**Comment by hsanjuan** [comment]
https://docs.google.com/spreadsheets/d/1rLxvRfdYohv-dhzVAo1xfeJOUa7uGfq6N_yyKw0iRw0/edit?usp=sharing
