### ISSUE TITLE
Missing exit status when command errors

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-cluster#174]
```
root@cluster-0:~# ipfs-cluster-ctl peers add $(cat /tmp/ipfs-cluster-server-addr)
An error ocurred:
  Code: 500
  Message: no connections to: QmNj4zW8SidPEU4amfAdgtaKjG3c2GffmzWWvCMeSYuRqp

root@cluster-0:~# echo $?
0
```

Exit code should have been something else than 0

**Comment by dgrisham** [comment]
@VictorBjelkholm I noticed this while working on https://github.com/ipfs/ipfs-cluster/pull/147, once that gets merged this should be fixed.

**Comment by VictorBjelkholm** [comment]
Doesn't `fmt.Errorf ` just prints the error rather than setting exit code? Feels like `os.Exit(nonZero)` has to be called somewhere if the exit code is to be set correctly.

https://github.com/ipfs/ipfs-cluster/pull/147/files#diff-26b121c3d48b28e2155589e577d025f5R478

**Comment by hsanjuan** [comment]
@VictorBjelkholm `checkErr` does that.

But actually, now that you mention, ipfs-cluster-ctl returns 0 in these cases because the request was successful (it was performed correctly, reached it's destination, and a well-formatted answer came back). Therefore cluster-ctl did its job. The error is from cluster not from the client. If you set json output the error will be in json, so your application can parse it. cluster-ctl returns non 0 exit status when something went bad and could not perform the request, in such case, output might not be parseable etc.

This is weird, but consistent with having a very clear line between what's cluster and what's a cluster api client.

That said, I don't like weird things, should probably be changed. @dgrisham your fix prevents the actual error response from being formatted to screen btw...

**Comment by dgrisham** [comment]
@VictorBjelkholm this should be fixed with https://github.com/ipfs/ipfs-cluster/pull/147, you'll get exit code 2 if an HTTP error code (>= 400) is received from the API call.
