### ISSUE TITLE
Integrate kubernetes testing in current ipfs-cluster pipeline

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#246]

**Comment by FrankPetrilli** [comment]
(Same as comment in #244)

An update as we wrap up Q4 2017:


> In a easy way, which can be automated and triggered remotely, obtaining the results. It should still be possible to run on minikube.

The task is triggerable by issuing an HTTP POST to the k8s master using the code in the following file: `https://github.com/ipfs/kubernetes-ipfs/blob/346a50aa442137903c2d07fd44ca96417526531e/ipfs-cluster/trigger-server.go`.

This is:

* Automatable (HTTP POST from any language)
* Remotely triggerable (Remote HTTP POST)
* Obtainable results (The HTTP POST response is the output of running the tests)
* Able to run on minikube (Just run it on the kubernetes node)

I made the above comment a few days ago requesting @hsanjuan's assistance with diagnosing the issues the cluster is still encountering on the real cluster. You've indicated that this runs flawlessly on minikube before, but we've seen issues that are universal. I'd like to validate the source of this error so that we can progress forward. If this is to your liking @hsanjuan, can we close this issue?
