### ISSUE TITLE
[Feature] Sync only if min replicas reached

### ISSUE THREAD

**Issue by segator** [ipfs/ipfs-cluster#277]
Could be interesting that ipfs-cluster only replicate a file if the minimum replicas are reached
Example:
max replication factor=7
min replication factor = 3

supose we have 10 nodes and 2 goes offline, nothing happens because we have 5 nodes with the replicated file.
but suppose 5 nodes that have same file goes offline so we have only the file replicated x 2, in this case is less than min replication factor so ipfs-cluster should automatically upload the file to a third node, if all the offline nodes go up again, the replication factor will be 8, so ipfs-cluster should remove the file from one of the nodes

**Comment by hsanjuan** [comment]
Yeah this is a pretty good idea, and would eliminate the problem that when one peer goes down, everything gets repinned somewhere else, and then when it comes up it's empty.

**Comment by segator** [comment]
I think it's necesary to have this feature implemented for large and untrusted storage nodes.

**Comment by segator** [comment]
min/max Replication factor is per cluster seems.
Where is the documentation of how it works? I would like to check it?
The cluster throw every event if min replication factor is reached alerting that a  object is replicating? and other event when finish the replication?
How exaclty works? if min repl factor is reached, cluster replicate +1 or until get the max replication factor? or how?
if the disconnected nodes come online and max repl factor is more than max , the object is deleted from any node?

**Comment by hsanjuan** [comment]
Hey @segator , min/max replication factor is per pinned item, with Cluster defaults (as before).

The [cluster guide](docs/ipfs-cluster-guide.md) has been updated accordingly, you can check https://github.com/ipfs/ipfs-cluster/commit/20705eaa09abe2cd0e74f69d7f237450a0c39abb for most changes.

> How exaclty works? if min repl factor is reached, cluster replicate +1 or until get the max replication factor? or how?

It will try to replicate to get the max, but will settle for less if it cannot reach it.

> if the disconnected nodes come online and max repl factor is more than max , the object is deleted from any node?

If a re-allocation was triggered (because it was pinned less than min), then the disconnected node(s) will no longer hold the CID and will unpin it when it comes online. If the replication factor did not cross the min, then allocations stay the same and it cannot be overpinned.

**Comment by hsanjuan** [comment]
Feel free to drop any additional feedback here @segator !
