### ISSUE TITLE
"received alert for freespace in" 

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#280]
I'm getting:

```
01:45:10.264 WARNI    cluster: Peer <peer.ID bAi2rn> received alert for freespace in QmS33gB... cluster.go:329
```

All the machines  it hears that from (2)have more than 10GB and 40GB free space though. is there a larger threshold here that it expects?

**Comment by hsanjuan** [comment]
I think this is because you have a lot of pinned things, and ipfs takes a long while to produce `repo stats`, so cluster metrics expire. We noticed during Christmas that `repo stats` is very expensive to run so often and it's a problem that needs to be addressed (I was going to start going about it this week).

In the meantime, you can significantly increase the freespace metric TTL in the config:

```
    "disk": {
      "metric_ttl": "600s", <--here
      "metric_type": "freespace"
    },
```

This will reduce the number of `repo/stat` calls.

**Comment by jbenet** [comment]
thanks! that helped

**Comment by hsanjuan** [comment]
I'll use this issue to track progress on resolving slow `repo/stat` calls from the cluster side (there will be another issue for go-ipfs).

Note to self: that warning message is misleading to the user and needs to be adjusted.

**Comment by hsanjuan** [comment]
ipfs issue at https://github.com/ipfs/go-ipfs/pull/4550

**Comment by ZenGround0** [comment]
@hsanjuan is this resolved?

**Comment by hsanjuan** [comment]
@ZenGround0 no, still ongoing but we're close

**Comment by hsanjuan** [comment]
https://github.com/ipfs/go-ipfs/pull/5010 finally
