### ISSUE TITLE
failure to see other peers

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-cluster#284]
- my local cluster node (rivendell) can connect to bootstrap node (celebdil).
- i get it to show up in the remote's `celebdil> ipfs-cluster-ctl peers ls`, but it shows as: `QmS3f5ei1fyZatgGNFViKzGeEhrJGkgbStv8PMs7KtTPng | rivendell | Sees 0 other peers` (odd, shouldn't it see one? and it does correctly show its addresses, so connection is going through)
- in turn, `rivendell> ipfs-cluster-ctl peers ls` just shows itself:
```
QmS3f5ei1fyZatgGNFViKzGeEhrJGkgbStv8PMs7KtTPng | rivendell | Sees 0 other peers
```
- so there's some connectivity problem here.
- pins dont work across them.

**Comment by hsanjuan** [comment]
It would seem rivendell is not aware of being part of celebdil raft's cluster at all. Was rivendell reset without removing it from celebdil? How were these two peers joined?

If the two peers were running independently and `cluster-ctl peer add` was used, this may be Raft not following through because of disjoint states. The standard workflow now is to use bootstrap with a clean state.

From the docs:

```
Remember: if you have a problematic cluster peer trying to join an otherwise working cluster, the safest way is to rename the ipfs-cluster-data folder (keeping it as backup) and to set the correct bootstrap. The consensus algorithm will then resend the state from scratch.
```

would be the best way to have rivendell join in the correct terms. I suggest running `peer rm <rivendel_id>` before in celebdil.

In any case, I'd need to know the workflow you followed setting up the cluster and adding the peers, as in current cluster versions this is an exotic situation to get to and I'd like to prevent it.

**Comment by hsanjuan** [comment]
Cleaning up. Closing this. I think the latest version makes it harder for this to happen. Re-open if follow up needed.
