### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by ekanath25** [ipfs/ipfs-cluster#411]
Hi there.

I tried to install ipfs-cluster from git :
git clone https://github.com/ipfs/ipfs-cluster.git

i got the below error when run make install
`make install
Downloading gx
The syntax of the command is incorrect.
make: *** [deptools/gx_v0.12.1] Error 1`

Please help me to solve this error. Thanks in advance

**Comment by hsanjuan** [comment]
@ekanath25 what version of Make are you using? What OS?

**Comment by ekanath25** [comment]
@hsanjuan I am using windows 10 and make version is GNU Make 3.81

**Comment by hsanjuan** [comment]
Is there a chance that you upgrade to Make 4.0?

**Comment by ekanath25** [comment]
@hermanjunge sorry, For windows make has 3.81 version only.

**Comment by hsanjuan** [comment]
@ekanath25 right, I don't think our Makefile can build anything on windows because it uses Linux tools and commands . You will need to build by hand:

1. Install gx and gx-go with "go get github.com/whyrusleeping/gx" "go get github.com/whyrusleeping/gx-go"
2. in the repo folder: gx install --global
3. gx-go rewrite
4. cd ipfs-cluster-service; go install
5. cd .. ; cd ipfs-cluster-ctl; go install

Something along those lines..

**Comment by hsanjuan** [comment]
Hi, we have documented how to install manually (in Windows): https://cluster.ipfs.io/documentation/download/#windows-and-manual-installation

Sorry, but it is very hard to help if you get an error but don't say what error. I'm closing this for the moment. Please re-open if you need more help.
