### ISSUE TITLE
[Daemon] Do not load API components which have been removed from the config

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#452]
#### Basic information

* [x] Type (mark as appropiate):
  * [ ] Bug
  * [x] Feature request
  * [ ] Enhancement

#### Description

We should be able to initialize Cluster with multiple API components.

As a nice-to-have, the `config` module should tell us when no configuration exists in the JSON for a certain component, and use that as an indication to decide which components are used when creating the `Cluster` object from `ipfs-cluster-service`.

**Comment by hsanjuan** [comment]
This is mostly done. The nice-to-have part is the only thing missing from this. @kishansagathiya you can put this on your list, but we can wait til we release another version or two and remove current backwards compatibility hacks.

**Comment by kishansagathiya** [comment]
From going through config code again, we might need to change how we are handling config at the moment. 
Currently we start all components (RegisterComponent) without even looking at what exists in service.json.

This is what I am thinking:-
1. Before anything else, read `service.json` to identify which components it has.
2. Register only those components (instead of all)
3. The process after this could be same as what we have right now.

**Comment by kishansagathiya** [comment]
It would be useful to not limit this only for API components. We would have to make sure in Validate() that all required components are present.

**Comment by hsanjuan** [comment]
You can't read sections in `service.json` without registering components. Default configurations are generated for empty sections though, so you can then pretty much know if some section was not even there. 

Perhaps the config manager can keep track on whether a config was defined or not at that point (if it had to generate a default, then it was not defined). We can use that knowledge when creating APIs (and other optional components in the future).
