### ISSUE TITLE
Do not attempt to push coverage in repository forks

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster#465]
#### Basic information

* [x] Version information (mark as appropiate):
  * [x] Master
  * [ ] Release candidate for next version
  * [ ] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`

#### Description

When someone forks this repository and sends a PR, our travis script tries to push coverage to coveralls, but since people forking the project has no access to the TOKEN, this fails and the whole travis job with it. We should be able to detect that a build is not happening in the original repository and avoid failing the whole build because of that. If this is not easy/possible. in the worst case, we should just ignore `goveralls` failures.

**Comment by Laevos** [comment]
@hsanjuan  So since the only test that's causing the failure here is `$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN`, and `go test -v -coverprofile=coverage.out -covermode=count ./...` completes successfully, should we break the former out into a seperate step? Then it'd just be a matter of tagging the step as conditional (https://docs.travis-ci.com/user/conditional-builds-stages-jobs/) and adding `if: fork = false`. The alternative would be to just mark the entire existing step as conditional, which seems less desirable.
