### ISSUE TITLE
Only last file is pinned while adding multiple files in IPFS cluster ADD REST API

### ISSUE THREAD

**Issue by aswin-ideas2it** [ipfs/ipfs-cluster#527]
In IPFS cluster 0.5, While adding multiple files in IPFS cluster through the new ADD REST API endpoint,

/add?replication-min=<min_replication>&replication-max=<max_replication>

Hashes are returned for all files, but only the last file is getting pinned.

Eg:
Its returning the below response when uploading 5 files,

{"code":0,"message":"","Name":"nomao-saeki-33553-unsplash.jpg","Hash":"QmSEWECV3JC3pRdapQtzxoX94yyqcAqRAQJNCRbWcSLiQF","Size":"1766750"}
{"code":0,"message":"","Name":"4.jpg","Hash":"QmTD5St6KjgyuAhGrLWfPo2mMBeR5uVSzBbi4YDVKERrdR","Size":"3034341"}
{"code":0,"message":"","Name":"3.jpg","Hash":"QmWasabYV5FtWrbCpujGDQEfjdh5PMAkEWXtSkqy6JsRZG","Size":"2010112"}
{"code":0,"message":"","Name":"2.jpg","Hash":"QmVKK462oxmW2xW3JcXNqHGM2qvJBWR7zWKJGUcV4GwZUB","Size":"1286719"}
{"code":0,"message":"","Name":"1.jpg","Hash":"QmNy7VZNMLwWttDGZXacCgv8aizkyVoX5LRC1qPmuNV6S3","Size":"2977283"}

But only the last file is getting pinned. 
i.e, {"code":0,"message":"","Name":"1.jpg","Hash":"QmNy7VZNMLwWttDGZXacCgv8aizkyVoX5LRC1qPmuNV6S3","Size":"2977283"}

**Comment by hsanjuan** [comment]
I checked this. I cannot come up with a nice way to detect that many files have been added and that the last file added is a not folder wrapping them all. If we wanted auto-wrap:

* A) We need to check that we're adding several files
* B) We need to check that we are not adding a wrapping folder, that is, that the last added file is not already a directory wrapping the previous added files.
* C) In that case we can wrap the result in a new directory, but otherwise we should only wrap if the user requested it.

It turns out checking that the last file, when it's a directory, is a not a parent of the previously added files is not super obvious. I think working on this is overkill, as in the client side it is very easy to know which data you're adding and how you want it pinned (that's why our client sets this right). So, users should set `wrap-in-directory` when they want to wrap things.

I don't think `go-ipfs` handles this case either so I think I will close it as won't fix.
