### ISSUE TITLE
Hash (ipfs-cluster) vs hash (go-ipfs) | capitalised vs lowercased

### ISSUE THREAD

**Issue by damirka** [ipfs/ipfs-cluster#534]
System:
- os - linux
- ipfs-cluster version 0.5.0
- go-ipfs version 0.4.17

Hello, we've been migrating to ipfs-cluster and ran into an issue with JSON response on `/add` method. **go-ipfs** implementation uses lowercased keys in JSON while **ipfs-cluster** uses capitalised.

Response from IPFS-CLUSTER:

```JSON
{ 
    "Name": "QmYkGooyRZLpHGAiWeZG3QdU2GAaxW9qpkMzz8yFMgNRjK",
    "Hash": "QmYkGooyRZLpHGAiWeZG3QdU2GAaxW9qpkMzz8yFMgNRjK",
    "Size": "22" 
}
```

Response from GO-IPFS:

```JSON
{ 
    "name": "QmYkGooyRZLpHGAiWeZG3QdU2GAaxW9qpkMzz8yFMgNRjK",
    "hash": "QmYkGooyRZLpHGAiWeZG3QdU2GAaxW9qpkMzz8yFMgNRjK",
    "size": "22"
}
```

I know this might seem a little bug but it makes inconveniences and isn't that obvious.

**Comment by lanzafame** [comment]
@damirka thanks for catching this :+1:

**Comment by lanzafame** [comment]
@damirka Actually, I was just trying to reproduce this and I am getting uppercased json keys back from go-ipfs v0.4.17, same as from cluster:

```sh
$ ipfs version
ipfs version 0.4.17
$ curl -F file=@test.file "http://localhost:5001/api/v0/add?recursive=false&pin=true&cid-version=0&hash=sha2-256"
{"Name":"test.file","Hash":"QmShBmhvEZ1dDwPvLvpjimRW76AQrVz3fbpZYwsqNJN2Xh","Size":"18"}
```

I am not sure where the change is occurring for you, how are you calling the endpoint?

**Comment by damirka** [comment]
@lanzafame you are right. Sorry. It seems the real issue is with js-ipfs-api client. Can't be sure before proper testing, but gonna test it soon.

**Comment by hsanjuan** [comment]
Ok. We have the Cluster Rest API `/add` endpoint and we have the IPFS Proxy `/add` endpoint.

The API `/add` should return lowercase, because that's the JSON API format we use across the endpoints. This API does not attempt to mimic ipfs, but it is convenient to return similar things since we share codepaths and it's nice to have similar behaviours.

However the proxy `/add` endpoint, which we intercept, should return Uppercase because it should mimic ipfs, and **it currently doesn't**.

@damirka which endpoint are you using? (or which one you would like to use?)

There is a bug in the proxy endpoint at least, so we should fix that.

**Comment by damirka** [comment]
@hsanjuan me (or we) do use proxy endpoint. Is there any chance you could fix it in nearest future?

**Comment by hsanjuan** [comment]
@damirka yeah will work on it asap

**Comment by hsanjuan** [comment]
ohh, I think it is `js-ipfs-api` that translates those objects to lowercase: https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#javascript---ipfsfilesadddata-options-callback

Yes, indeed: https://github.com/ipfs/js-ipfs-api/blob/master/src/utils/file-result-stream-converter.js#L3

It seems that your issue is not related to a mismatch in our response formats.

**Comment by hsanjuan** [comment]
Please re-open if needed
