### ISSUE TITLE
Where can I find the IPFS Cluster Weekly Sync notes?

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-cluster#608]

**Comment by hsanjuan** [comment]
I'll send them in private since I don't want a random internet troll to mess them up.

**Comment by hsanjuan** [comment]
actually, we upload them every few weeks to: https://github.com/ipfs/pm/tree/master/meeting-notes/2018

**Comment by diasdavid** [comment]
The last upload was 6 months ago 

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1211152/47993590-2017be80-e0f0-11e8-95ca-094983213212.png">

Is this correct?

👍 for uploading them to ipfs/pm. Bonus points if it gets done through a PR

**Comment by hsanjuan** [comment]
Probably correct. I probably don't send them with a PR because there is nothing to "review". We're just archiving.

**Comment by hsanjuan** [comment]
Hey, can you explain if there is a problem you are trying to solve? Our notes are written prior to meetings with the objective of making the meetings focused and useful, not meant to be read after our meetings (their aim is not to log the meeting itself).

I have the feeling this works well for us. Are we doing something wrong that we need to change how we work? What successes are you talking about and how do they apply to this WG? Can you outline what kind of review you want to perform and what kind of content you want to add to our notes?

Note that this WG is slightly special because of the small size, the timezone of their members and its lack of dedicated PM, so what others do may or not be useful for us, but I'd like to solve any problems that there are.
