### ISSUE TITLE
Apparent security design flaw regarding secret key usage

### ISSUE THREAD

**Issue by hugbubby** [ipfs/ipfs-cluster#610]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [X] Master
  * [X] Release candidate for next version
  * [X] Latest stable version
  * [X] An older version I should not be using
* [x] Type (mark as appropiate):
  * [X] Bug
  * [ ] Feature request
  * [] Enhancement
* [x] Operating system (mark as appropiate):
  * [X] Linux
  * [X] macOS
  * [X] Windows
  * [X] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description
While reading the documentation, at first glance, the effective authentication system for modifying the pinset or adding new nodes seems extremely precarious. I have only been introduced to this project's existence this morning, but my understanding is that the security of the entire cluster is dedicated to the sanctity of one secret key, present on all peers. The compromise of any one peer on the cluster would allow an attacker to unpin everything from the network. That is an unacceptable risk for large scale usage, much more prominent than some performance cap. Imagine if the availability of every file on Dropbox rested on the complete security of an environmental variable on every single one of their storage servers. Untenable.

Along with this, I am also under the impression that the same secret key that is used to add a server to the network, to accept pins, etc., is also the same secret key that is used to update the global pinset. Shouldn't these privileges be separated? There should be a key/ticket that allows one to be added to the network as a storage node, and there should be a key/ticket that allows one to update the global pinset that the network pins, but there is no reason to couple these privileges into the same key. 

Feel free to inform me if these opinions are misguided in any way - I'm evaluating the usefulness of ipfs cluster for an upcoming project and have never actually maintained one before.

**Comment by hsanjuan** [comment]
Hi, you are mostly right. There is no authorization mechanism in cluster RPC endpoints (authentication being provided by libp2p) at all. The libp2p private network key (the cluster secret) is a bad replacement. We are planning to add this rather soon.

Note that if your "signature" does not make things any better. If the signature is compromised, that would allow the attacker to impersonate your peer anyway and do whatever that peer could do before.

I know this approach is done in things like puppet or icinga, but they are centralized setups which need to provide authorization, authentication, and secure the channel. I know it is not always obvious, but the libp2p provides peer authentication  and secure channel by design. It is not based on a centralized certificate authority, but it does use public/private key pairs.

What Cluster needs is fine-grained RPC endpoint authorization that lets peers to trust/untrust other peers (which is the equivalent of revoking a signed certificate), and to open, close endpoints accordingly. And that is a way simpler problem to solve that building another authentication layer on top with yet another key pair.

**Comment by jedahan** [comment]
I like how syncthing makes every device explicitly authorize each others ids, as shown [in their docs](https://docs.syncthing.net/intro/getting-started.html). Not sure if that matches with @hsanjuan's description but it seems to.

**Comment by hugbubby** [comment]
> Note that if your "signature" does not make things any better. If the signature is compromised, that would allow the attacker to impersonate your peer anyway and do whatever that peer could do before.

No, because the **ticket** to be added onto the network can only be used once. The private key used to sign the ticket could be compromised, but it's much easier to maintain control over one private key than it is to maintain control of a secret key spread around the network.

**Comment by hugbubby** [comment]
> Note that if your "signature" does not make things any better. If the signature is compromised, that would allow the attacker to impersonate your peer anyway and do whatever that peer could do before.

Are you under the impression that the signed tickets could be replayed? I'm not sure what you mean by this.

**Comment by hsanjuan** [comment]
I will close this for now (doing issue clean-up). Some concerns here will be addressed with #710 .
