### ISSUE TITLE
/monitor/metrics/{invalid name} should respond with BadRequest

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#758]
Currently `GET http://localhost:9094/monitor/metrics/invalid_name` responds with OK(200) and an empty array. Ideally it should respond with BadRequest(400) and empty body.

**Comment by hsanjuan** [comment]
This is a good reference about http codes: https://www.restapitutorial.com/httpstatuscodes.html

This is not a bad request. The request is perfectly understood. It's just a request for a metric that does not exist because no peer issued it. You may argue for a 404, but it would imagine that in the future supporting several allocators may imply potentially arbitrary metrics of different names, and I find it hard to argue that the http api component should be aware of which actual metrics other components are broadcasting.. so I don't find it wrong to return a 200 with empty list if you request for a metric that no one is issuing.
