### ISSUE TITLE
`/pins/recover` should work without the local flag as well

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster#763]
Currently, for `/pins/recover` has local flag mandatory and it has to be `true` (i.e, throws bad request if not passed or passed but other than true)

This is equal to not having the flag. I think recover should work without the flag as well.

**Comment by hsanjuan** [comment]
This would mean recover triggered in all peers for all pins (not just modifying the current behaviour to work without the flag). One of the reasons this is now allowed now is because if pins need recover on a peer there might be issues to be resolved on that peer. But that's not a very strong reason.

I leave this as low prio though, as there is a workaround by triggering `/recover/cid` requests.
