### ISSUE TITLE
Onboarding Question Collection

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/ipfs-cluster#79]
Here are a few questions I have had at various points while working out how ipfs-cluster works.  

What exactly are peers communicating to each other?  

What is the division of labor between an ordinary peer and the cluster leader?  What extra work does the cluster leader do? 

What is the purpose of bootstrapping in ipfs-cluster-service?  Is this the way for a single node to begin its own cluster?

What does the comment "// The only way I could make this work" in ipfs-cluster/main.go's init function referring to?

What is the purpose of the --leave flag and why is it possible for a node to be considered part of the cluster when its ipfs-cluster-service process is no longer running?  Why is --leave not default?  It sounds like if a node does not leave on shutdown it can lead to problems, so what is the beneficial use case of leaving it in?

From context clues it seems like ipfs-cluster in the future hopes to provide options for consensus, ipfs connections and monitors?  Is this the case?  If so what is the purpose of having these options?

ipfshttp appears to communicate with an ipfs daemon listening a local port through an http api.  Does the ipfs daemon have other methods of communication and its just a matter of cluster not implementing clients?  I suspect this is the case because the ipfsconn folder seems to abstract away ipfs connections from an http api, however the service binary directly calls ipfshttp, so maybe the ipfsconn/ipfshttp hierarchy was intended to mean something else.

Thanks, and more to follow!

**Comment by hsanjuan** [comment]
> What exactly are peers communicating to each other?

Peers communicate at several levels:
  * The whole consensus layer (raft, leader election, heartbeats etc), is handled by hashicorp.Raft. This is wrapped by `go-libp2p-raft` which implements the `go-libp2p-consensus` interface and attaches a libp2p transport to Raft.
  * On the ipfs-cluster level, components communicate which eachother using the `RPC API`. This uses `go-libp2p-gorpc` to send messages around.
    * Most rpc requests between componenets will happen locally on the same peer. i.e. the rest api component asks the main component to Pin() something.
    * Some RPC requests are sent to other peers. i.e. when pinning something, the node that receives the requests forwards it to the Raft leader, because only the Raft leader can commit something to the log. Other requests involve broadcasts to other peers: Peers() sends RPC requests to all peers to obtain the information provided by their ID() method, puts it together and returns it.

> What is the division of labor between an ordinary peer and the cluster leader? What extra work does the cluster leader do?

The leader is the only one that can commit to the log. Therefore a Pin/Unpin requests, PeerAdd/PeerRm requests are forwarded to the leader by the consensus component.

The leader is also the one receiving monitoring metrics and detecting if a node has gone down, triggering repinning operations when that happens and providing the last metrics to decide on pin allocations when a peer requests them.

Other than that, every peer does its own job when a requests lands on it.

> What is the purpose of bootstrapping in ipfs-cluster-service? Is this the way for a single node to begin its own cluster?

Bootstrapping is a way to facilitate that a node discovers the rest of the peers in the cluster. You can either manually fill-in all the cluster members in the configuration, or you can "boostrap" from an existing cluster member. When bootstrapping, a peer will contact the bootstrap node and receive the list of all the other peers.
It will also get added to the list of peers for everyone else (via a special raft log entry).

> Is this the way for a single node to begin its own cluster?

No, it's a way to join an existing cluster. To begin a cluster, you just need to start it without any cluster peers or bootstrap peers in the configuration.

> What does the comment "// The only way I could make this work" in ipfs-cluster/main.go's init function referring to?

Good question. Let's see. Yes, when building `ipfs-cluster-service` there is this `-ldflags "-X main.commit=$(shell git rev-parse HEAD)"`. I had to use `main.commit` bc `ipfscluster.Commit` did not work, so it would not set the commit variable correctly without having a variable for it in `main`

> What is the purpose of the --leave flag and why is it possible for a node to be considered part of the cluster when its ipfs-cluster-service process is no longer running?

The --leave flag removes a peer from the consensus when it is shutdown. Otherwise, other peers will still count on it and the leader (raft mostly) will start complaining because it cannot receive the heartbeats from that cluster peer. A peer can be part of the cluster when it's not running if it has been stopped without leaving/being removed or if it has crashed. In both cases, it's not good.

> Why is --leave not default? It sounds like if a node does not leave on shutdown it can lead to problems, so what is the beneficial use case of leaving it in?

It's not default (and it's a hidden cli flag, although it's documented in the configuration), because the process of adding a peer and removing it is complicated, and in unhealthy clusters it might create bad situations. It also might lead people think that they can leave cluster A, join cluster B etc. and re-using raft log from cluster A in cluster B is probably not a good idea. Much of the problem here is how hashicorp.Raft handles consensus peers updates (special entry to the log etc.). I think they have rewritten this part in the non-yet stable dev branch. Additionally, you can always use `peer rm` to have a peer leave (which is more explicit and better for informing the user about any errors than just autoleaving).

It's a long story, but in the end peerAdd/peerRm/bootstrap/etc are great for setting up a cluster, having new, clean peers join it etc, but the ideal is to have a cluster with a generally stable number of peers which are always running and operations which modify the set of consensus peers should be explicit. When the times come to update Raft to the new version, we will have to revisit all these operations and hopefully there will be a safer workflow. There's much to improve too on our side (safeguards etc), but this is part is quite tricky.

> From context clues it seems like ipfs-cluster in the future hopes to provide options for consensus, ipfs connections and monitors? Is this the case? If so what is the purpose of having these options?

Yes, these are components. Every component fulfils an interface so it should be easy to replace them (or provide alternatives). i.e. Raft will probably not scale too far, so it should be possible to provide a different consensus implementation. The monitoring component can probably be done way better etc.

> ipfshttp appears to communicate with an ipfs daemon listening a local port through an http api. Does the ipfs daemon have other methods of communication and its just a matter of cluster not implementing clients? I suspect this is the case because the ipfsconn folder seems to abstract away ipfs connections from an http api, however the service binary directly calls ipfshttp, so maybe the ipfsconn/ipfshttp hierarchy was intended to mean something else.

`ipfshttp` implements the IPFSConnector component, whose job is to talk to the `ipfs` daemon. It's a separate component because it's functions are well defined and it can be one. That said, you could implement other ifps connectors: say ipfs offers a different API at some point, or you are running a custom version of ipfs with some changes... You could also have a Connector which does `import "ipfs/core"` and launches directly the daemon from cluster. So in the end it's about having clear interfaces and being able to replace components with alternative/better ones in the future.

**Comment by ZenGround0** [comment]
Could you explain why components running on the same peer communicate over libp2p?  Is the implementation of a communication channel with goroutines in a different runtime similar enough to that of a communication channel in the same runtime that libp2p already had the necessary function calls?

**Comment by hsanjuan** [comment]
> From architecture.md "pin this CID with this allocation" is another type of log entry. Are there any others I should know about?

No, log entries are Pin/Unpin/AddPeer/RmPeer.

> What is the difference between ping and informer metrics?

Informer is a component which provides "custom" metrics which are used to decide where to allocate a pin. Currently it provides a datastore-size (`disk`) metric by default. "ping" is a metric used to detect if a node goes away unexpectedly.

>  I keep seeing references to the sync and recover operations on a CID. What are these operations? How does the clusters' state get out of sync with IPFS and what is the cluster recovering from?

`Sync` makes sure that cluster local state (PinTracker) reflects ipfs daemon state. Desync can happen for example by unpinning something directly on ipfs without cluster knowing, or when a pinning operation takes so long that it times out but eventually ipfs completes it etc. It should not be the case though. `Recover` triggers local re-pin/re-unpin in pins with error state. `Sync` and `Recover` do not happen automatically right now, but probably `Sync` should at least run from time to time.

`StateSync` makes sure that the consensus state is correctly tracked/reflected by the cluster local state (PinTracker). This happens regularly. It can be out of sync if a node misses out too many Raft log updates for whatever reason. On recovery, Raft will not send log updates one by one, but rather a full state snapshot. Because log updates are not sent, the Apply() operation does not run, and the PinTracker is thus not informed of changes. It also needs to happen on startup, once the raft log is synced completely.

**Comment by ZenGround0** [comment]
Hey Thanks for all the answers!

I have a few questions about work that needs to be done, specifically on testing ipfs cluster.  

From our earlier meeting you had a few bullet points outlining areas that need work, I have some clarifying questions about what each means / what solutions might look like.
1. Network tests and benchmarking
Does this mean recording ipfs cluster's performance in different network conditions i.e. high latency or low throughput?  Is there a tool I should be looking into for setting up network conditions for testing? Also what are the metrics we have in mind for measuring ipfs-cluster performance?  

2. Display connectivity and connectivity graph
I am unsure if this is a feature to be added to the binaries, or rather a tool to build for testing.

3. Sharpness test
What are sharpness tests?

4. Private network
Is this referring to building the binaries to work on private networks?  Is there some part of configuration that makes handling private networks hard?

5. Disk metric collection
I understand this, and from the captain's log it looks like it is partly implemented.  What further work is needed in this area?

6/7. Monitoring system improvements / open issues and feature requests
These are self-explanatory.

In addition to these clarifications is kubernetes-ipfs going to be useful for building the test cases that we need?  Also I see the travis.yml in the ipfs-cluster repo and I'm curious how adding new test cases will relate to CI.  Is the goal to launch a cluster when Travis runs and run the tests as part of CI?

**Comment by hsanjuan** [comment]
Here are the notes I wrote:

## State of the art

 * There is https://github.com/ipfs/kubernetes-ipfs/tree/ipfs-cluster-dev which runs some tests on ipfs-cluster. With enough capacity they are good point to start running them with larger cluster sizes (20, 50, 100) and see what happens. Should ask @frankpretrilli if we have a big enough kubernetes cluster for that
 * These tests don't really offer a way to disconnect a node and bring it back later. One line of work is to figure out the best way to do this within the tests: starting a cluster node needs a follow up command to add it to the rest of the cluster (ipfs-cluster-ctl peer add). This is done in `init.sh` while launching the cluster (outside the tests): https://github.com/ipfs/kubernetes-ipfs/blob/ipfs-cluster-dev/ipfs-cluster/init.sh#L39
 * There is a list of tests to implement: https://github.com/ipfs/ipfs-cluster/issues/12#issuecomment-280231842
 * Also, I have not figured out how to make any metric collection in kubernetes-ipfs as it happens with the regular ipfs tests (which run prometheus and graphana on the side I think: https://github.com/ipfs/kubernetes-ipfs/blob/ipfs-cluster-dev/prometheus-manifests.yml). ipfs-cluster does not provide any debugging/metric collection endpoints at the moment either, this should be done too in the same way ipfs does it.
 * kubernetes-ipfs may not be the only way. It may be possible to test and collect metrics in more rudimentary ways, i.e. by having a few EC2/DigitalOcean VMs (terraform comes handy), deploying to them with Ansible/Docker and running commands via ssh, or via a script fetched from somewhere etc.  But still, would be nice if kubernetes-ipfs gets improved and to the point where it works for everyone and everyone benefits rather than having custom solutions per project. If you come up with better ideas we can look at them.


## Key objectives in testing

* Complete the list of tests in ipfs-cluster and propose more (https://github.com/ipfs/ipfs-cluster/issues/12#issuecomment-280231842)
* Add tests for the ipfs-proxy (easy)
* Determine whether a cluster behaves well when there are peers not responding/offline. What happens if 50%-1 peers are down on a large cluster? How do cluster commands do (peers ls, status, sync)? Is pinned content correctly re-allocated?
* Add sharness tests for cli tools

## Key objectives in benchmarking

* Determine how big can a ipfs-cluster grow and what happens when it gets close to limits
* Determine what is the limiting factor in pin-ingestion for cluster for different cluster sizes. Affecting variables:
    * Pinned object size: ipfs will take longer to fetch and pin larger content.
    * ipfs can only pin one thing at a time. cluster peers only submit pins one at a time. There is a queue (200 items i think).
    * Replication factor
    * Size of the cluster (means more broadcasting from the Raft leader).
    * Note: pin is a two phase thing: first phase is to commit to the consensus log. A Pin() operation returns OK if that works. Second phase is for PinTrackers to get ipfs to pin the log entry. Second phase is async. PinStatus is PINNING while a pin is still waiting to be pinned on ipfs, or PINNED when it's done. Therefore benchmarks should include the duration of each phase too.
    * I expect Raft to start breaking when it starts hitting timeouts: https://godoc.org/github.com/hashicorp/raft#Config . We use defaults mostly (https://github.com/hashicorp/raft/blob/master/config.go#L90). It should be good to come up with configuration values adapted to our usecases.
* Determine how much bandwith a cluster peer needs, depending on the cluster size
* Determine how pin ingestion and other operations are affected when the cluster is unhealthy (not all nodes available).

Additional:

* https://github.com/chriscool/sharness
* @FrankPetrilli is the person to ask questions if you need capacity to run large tests in an existing real kubernetes cluster. @frankPretrilli: @ZenGround0 will be working on some cluster tests. At some point we'll probably need a way to run 20, 50 or 100 nodes on kubernetes.
* Tests where network constrains come into place (latency, bandwidth) are also a great thing!

**Comment by hsanjuan** [comment]
> Private networks / PNets
This is related to using libp2p private networks with cluster, which wrap libp2p connections with a pre-shared-key. This allows to lock-down a cluster to a given set of peers which now a key. Right now, anyone can join if they can contact a cluster peer's libp2p endpoint. It is a recently added feature to libp2p.

> Disk metric collection. I understand this, and from the captain's log it looks like it is partly implemented. What further work is needed in this area? 

Yeah, this is done... for the moment not much else is needed here.
