### ISSUE TITLE
REST API: Allow to disable unpin (and other endpoints)

### ISSUE THREAD

**Issue by volodyad** [ipfs/ipfs-cluster#793]
Question is related to the #750 
We have 10 nodes cluster. If someone get access to the node - we need to be sure that data will not deleted from the all nodes.
Could we prevent unpin operation on a cluster configuration level? In this case even if someone get access to the node - he will not be able to force file deletion form all nodes.
As alternative - maybe cluster secret could contain information about allowed operation in the cluster.

**Comment by hsanjuan** [comment]
First, I should say that if someone "gets access to the node", depending on what that means, the amount of problems and security issues involved is much larger than being able to unpin.

Therefore I'm turning the problem into how to provide a limited API to users which only supports certain commands so that users with access to that API are limited in the things they can do with it (i.e. only pin).

There is a possibility of disabling certain REST API endpoints by listing them in the configuration so that users can run a limited API (without `unpin`, or without `peers ls`). This however will allow no-one, even administrators, can use those endpoints (unless they re-enable them).

This is an authorization problem in the end. While there has been some discussion in #621, the favored solution here is for users to run a layer on top of the Cluster API which satisfies additional authorization, authentication and usage constraints. For example, instead of interacting with the Cluster API they can do it with a pinbot like (https://github.com/ipfs/pinbot-irc) which only allows pinning, or an nginx reverse proxy can be configured to only allow certain endpoints.

Disabling endpoints listed in the config would however be do-able without much trouble (maybe hand in hand with running multiple REST APIs side by side - one for admins, other for users). But it still a patch over the fact that we don't want to do advanced authorization mechanisms inside Cluster but as something built on top (and re-usable for other APIs).

@lanzafame @kishansagathiya opinions?

**Comment by kishansagathiya** [comment]
REST APIs run locally. If someone has access to the node, they can very well recompile the binary, reconnect to the cluster and call the edit REST API. What we want to avoid is to not have any effect of that call on other machines, like something on the consensus level.

**Comment by kishansagathiya** [comment]
For a private cluster with a leader, this might be a good feature. Unpin is more critical than Pin. Getting your storage filled by random pins isn't as bad as loosing all your data.
It would make sense to make `Unpin` only available to the admin. Having to compromise one extra secure node is a better situation than having to compromise any one node.

I don't think this is as simple as just disabling the API. If the node is compromised, wouldn't they be able to run APIs on ipfs too?

**Comment by hsanjuan** [comment]
We are not talking about someone accessing the node anymore, but about limiting the API surface for people accessing the API: `Therefore I'm turning the problem into how to provide a limited API to users which only supports certain commands`

**Comment by lanzafame** [comment]
> Therefore I'm turning the problem into how to provide a limited API to users which only supports certain commands

@hsanjuan this is user management, beyond which we can provide via basic auth.

**Comment by hsanjuan** [comment]
> > Therefore I'm turning the problem into how to provide a limited API to users which only supports certain commands
> 
> @hsanjuan this is user management, beyond which we can provide via basic auth.

Not about doing it for specific users, but as a whole. i.e. being able to run apis with less endpoints. not related to auth. It's a bit like IPFS gateways, which you can let the users browse-through. You could have ipfs cluster gateways, which you can only pin with.

**Comment by hsanjuan** [comment]
> > > Therefore I'm turning the problem into how to provide a limited API to users which only supports certain commands
> > 
> > 
> > @hsanjuan this is user management, beyond which we can provide via basic auth.
> 
> Not about doing it for specific users, but as a whole. i.e. being able to run apis with less endpoints. not related to auth. It's a bit like IPFS gateways, which you can let the users browse-through. You could have ipfs cluster gateways, through which you can only pin.

**Comment by volodyad** [comment]
Our main concern - if someone will get access to the node and run unpin operation on the cluster. In this case after ipfs garbage collect we will lose all our data. Os if any node is compromised we could lost everything. Case that malicious user will pin some dummy data or retrieve encrypted file are not so critical for us.
Regarding node recompile - user will be able to recompile only current node, on all others unpin will be disabled.
Maybe there is some approaches for ipfs data backup?

**Comment by hsanjuan** [comment]
OK @volodyad , yes you have point. Let me think about this, I will come up with an approach.

**Comment by lanzafame** [comment]
> Not about doing it for specific users, but as a whole. i.e. being able to run apis with less endpoints. not related to auth. It's a bit like IPFS gateways, which you can let the users browse-through. You could have ipfs cluster gateways, which you can only pin with.

@hsanjuan I see what you mean, I am not sure it really meets the usecase that @volodyad  is after but it would be useful in its own right.

**Comment by hsanjuan** [comment]
I have thought that the solution for this is an additional config option for the IPFSConnector which makes `Unpin` in that component always return an error. Nothing can unpin anything from IPFS through cluster if the IPFSConnector `Unpin` method refuses to call IPFS.

**Comment by volodyad** [comment]
Hello, do you have any updates when it could be implemented?

**Comment by hsanjuan** [comment]
> Hello, do you have any updates when it could be implemented?

Between one and 4 weeks.
