### ISSUE TITLE
Cluster graph command should distinguish between trusted and untrusted peers

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#800]
**Describe the feature you are proposing**

The output of `ipfs-cluster-ctl health graph` should distinguish between which peers are in the trusted peerset and which are not.

**Comment by kishansagathiya** [comment]
Do you mean that it should show which peers which are trusted by us and which are not?

**Comment by hsanjuan** [comment]
Yes, by coloring them differently for example.

**Comment by kishansagathiya** [comment]
I think showing the peers which are trusted/untrusted by local peers should be enough. We don't need to show trust links between any other peers.

**Comment by hsanjuan** [comment]
> I think showing the peers which are trusted/untrusted by local peers should be enough. We don't need to show trust links between any other peers.

Correct. You get a PNG and it shows trusted peers in green and untrusted in red (for example)

**Comment by kishansagathiya** [comment]
Something like this
Black for self
Green for trusted
Blue for untrusted
Golden for IPFS
![xyz](https://user-images.githubusercontent.com/10185999/64853894-9d805980-d646-11e9-983a-17e868c9c7e2.png)

**Comment by hsanjuan** [comment]
Yes, can you now prettify labels? Research if there is a way to include a legend about the colors? See if there is a way to "group" a cluster peer with it's ipfs daemon inside a box or something?

**Comment by kishansagathiya** [comment]
I am planning these changes
- cluster nodes solid and IPFS hollow, 
- trusted node dark green and untrusted light green
- Instead of using labels like `<peer.ID Qm*IrV9Se>`, use last five characters
- for out own node use `Self` as label

From what I have read, you can't create box around two nodes. You can group them together, but that only makes sure that the arrow between two nodes is straight. It would look like this
![what](https://user-images.githubusercontent.com/10185999/65035756-9b303f00-d967-11e9-9649-5670c229d7a0.png)

But using subgraphs and using rank attribute for that subgraph makes thing quite prettier 
![what](https://user-images.githubusercontent.com/10185999/65035897-e5192500-d967-11e9-96e2-b2e3b83dcc77.png)
