### ISSUE TITLE
[CRDT] Untrusted Peers can remove pins and this causes weird situations

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster#803]
Untrusted peers can gain control of pins if they are the only ones allocated for that pin.
Forced example
```
$ ipfs-cluster-ctl -l <trusted_peer> pin add -r 1 --allocs <untrusted_peer> <hash>
$ ipfs-cluster-ctl -l <untrusted_peer> pin rm <hash>
# works!!!
$ ipfs-cluster-ctl -l <trusted_peer> pin ls
<hash> |  | PIN | Repl. Factor: 1--1 | Allocations: [<untrusted_peer>] | Recursive
# trusted peers still think it is around
```

This is an issue in the case of a cluster that has more untrusted peers than trusted peers, which is the model we are going for.
In a cluster that has a default replication of 3, uses the freespace allocator, has 10 peers, 4 trusted, 6 untrusted, once 3 of the untrusted peers have more freespace than the trusted peers they will get allocated all the pins and will have full control over those pins, with the trusted peers having no idea whether the pin is actually on the untrusted peer. 

//cc @hsanjuan we need to figure out how we are going to approach this scenario

**Comment by lanzafame** [comment]
So since I got `ipfs-cluster-ctl status` working again :), the output to the above scenario is
```
$ ipfs-cluster-ctl status
<hash> :
    > <trusted_peer>-1          : REMOTE | 2019-05-29T07:15:25.114565985Z
    > <trusted_peer>-0          : REMOTE | 2019-05-29T17:15:25.106086092+10:00
```
Note the lack of the <untrusted_peer> indicating that at some level, cluster is able to determine that there is only remotes left and something needs to be done about it.

**Comment by hsanjuan** [comment]
There are several parts here. First, any peer in a CRDT cluster can unpin or pin anything. But that modification will not propagate to other peers and will only affect its own state (because it's not a "trusted" peers for others). I'm not sure that is a bug.

Secondly, "trusted" peers or anyone actually asking people to pin things and expecting them to be pinned should be careful that there is no way to force "allocated" peers to pin. They can either, unpin that (as above), or simply fake the fact that they are pinning.

Thirdly, the `status` output does not show the untrusted_peer. This is because the PinTracker.Status call in that peer will only return information for its pins. And since it unpinned that `hash`, it's not in the list at all. This is "normal" behavior but not obvious at all (very bad UI).

I think the main problem here is that we allow what should be 'untrusted' peers to modify their pinsets normally and this is bad UI. If we can declare some peers as "followers" we could simply error when trying to pin/unpin and this would prevent accidents and getting into all these situations in many cases.

Should we make this a configuration option in `crdt`? A different way of doing this is requiring that the local peer ID is in the `trusted_peers` list, and failing to do anything if not. Basically, if you want to make modifications to the shared state you need to trust yourself.

**Comment by hsanjuan** [comment]
To move forward here:

* Add hidden `mode` to the `crdt` config
* Defaults to empty - is hidden
* If set to `follower`, LogPin/LogUnpin error saying the peer is in follower mode

This should allow to distribute configurations in follower mode which offer the right UX.
