### ISSUE TITLE
What is peer behaviour on cluster shutdown/restart?  

### ISSUE THREAD

**Issue by bgadmin** [ipfs/ipfs-cluster#83]
When there is cluster with let's say two peers and one of them or both gets shutdown for some reason, do peers stay remembered and connect automatically on startup? 

I suppose they are automatically saved into service.json file in cluster peer section?

Thanks !

**Comment by hsanjuan** [comment]
> I suppose they are automatically saved into service.json file in cluster peer section?

Yes that is the default behaviour (you can check it).

If a peer is shutdown cleanly and the `leave_on_shutdown` option is set to true, the that peer will leave the cluster/consensus (and `cluster_peers` will be emptied). On startup it needs to use the `bootstrap` list or be added from a member of the cluster with `peers add`.

If a peer is shutdown cleanly and the `leave_on_shutdown` option is set to false, the peer will save current list of peers in `cluster_peers` and shutdown without leaving the cluster/consensus. This means that other peers will still try to contact it. In a 2-peer cluster, if one goes down, a leader election will be triggered and, since no majority is possible, no leader will be chosen, so many operations will fail (pins, unpins) in the meantime, but things will recover as soon as it comes back up.

Does that make sense to you or would you suggest improvements on this front?

**Comment by bgadmin** [comment]
@hsanjuan Thanks for fast response, this makes perfect sense, just wanted to double check.

No suggestions for now, this is awesome :+1: 

Where can "leave_on_shutdown" parameter can be specified?

**Comment by hsanjuan** [comment]
@bgadmin in ~/.ipfs-cluster/service.json

If you don't see this parameter, I recommend that you `ipfs-cluster-service -c /tmp init` and compare your version with the newly created one. It should create something like:

```
{
    "id": "QmXaNvRpnr3eNpSRAjhAF8yctGPPpxX1B2TetSzuPVyRbE",
    "private_key": "blabla....",
    "cluster_peers": [],
    "bootstrap": [],
    "leave_on_shutdown": false,
    "cluster_multiaddress": "/ip4/0.0.0.0/tcp/9096",
    "api_listen_multiaddress": "/ip4/127.0.0.1/tcp/9094",
    "ipfs_proxy_listen_multiaddress": "/ip4/127.0.0.1/tcp/9095",
    "ipfs_node_multiaddress": "/ip4/127.0.0.1/tcp/5001",
    "consensus_data_folder": "/tmp/data",
    "state_sync_seconds": 60,
    "replication_factor": -1,
    "monitoring_interval_seconds": 15,
    "allocation_strategy": "reposize"
}
```

Anything not specified will get defaults.

**Comment by hsanjuan** [comment]
please re-open if needed!
