### ISSUE TITLE
Problem with setting up cluster on private network.

### ISSUE THREAD

**Issue by Mukeshawal** [ipfs/ipfs-cluster#866]
i am trying to implement ipfs cluster in a private network and facing some problems.. i have already edited my service.json files and replaced all 127.0.0.1 with my private network ip 192.168.100.14 and similar to other node

after i start ipfs cluster service daemon in first node and in others by bootstrapping to first node i recieved log

19:13:33.909 INFO consensus: peer added to Raft: QmS5o4yTiyw8YmYUrLsdYUBvebnoQb9cKikdA46Sf98PXh consensus.go:393

19:13:33.918 INFO cluster: Peer added QmS5o4yTiyw8YmYUrLsdYUBvebnoQb9cKikdA46Sf98PXh cluster.go:672

which probably means peers were added. now when i do ipfs-cluster-ctl peers ls i get log

An error occurred:

Code: 0

Message: Get http://127.0.0.1:9094/peers: dial tcp 127.0.0.1:9094: connect: connection refused

why is it sending get request to 127.0.0.1 instead of the local ip i set in sevice.json file?? other thing is even when i try to use ipfs-cluster-ctl add then it sends post request to http://127.0.0.1:9094 .

am i doing any thing wrong??

**Comment by hsanjuan** [comment]
Hello, `ipfs-cluster-ctl` contacts 127.0.0.1 by default, which is the local loop interface. If your node is not listening on the localhost interface (because you say you configured to listen on a different interface), you probably need to use `ipfs-cluster-ctl --host /ip4/192.168.100.14/tcp/9094`.

I am not sure why you would replace all 127.0.0.1 with your private network interface though, unless you want to contact the API of each peer from anywhere in that network. The address that you need to adjust is the main `listen_multiaddress` which by default is `0.0.0.0`. There is more info about endpoint. ports and security: https://cluster.ipfs.io/documentation/security/ .

**Comment by Mukeshawal** [comment]
I seem to have misuderstanding about those endpoints.. thanks for your response!!
