### ISSUE TITLE
Add behaviour differers on 0.12.0-rc1

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-cluster#983]
**Additional information:**
 - OS: macOS & Linux
 - IPFS Cluster version: 0.11 vs 0.12-rc1
 - Installation method: dist.ipfs.io

**Describe the bug:**

I am running a daily build for `/ipns/xkcd.hacdias.com` and posting the information to IPFS Cluster for pinning. Since last night, when it got upgraded to 0.12-rc.1, the HTTP API for ADD stopped returning the top-level CID for the directory.

I run the commands manually on my computer and noticed this:

With **0.11**:

<img width="1552" alt="Screenshot 2019-12-17 at 16 03 37" src="https://user-images.githubusercontent.com/5447088/71007464-57281400-20e7-11ea-9f91-b06715853165.png">

With **0.12-rc1**:

<img width="1552" alt="Screenshot 2019-12-17 at 16 04 23" src="https://user-images.githubusercontent.com/5447088/71007463-57281400-20e7-11ea-81c9-1a61bda17f5f.png">

---

We can see the name `dummy` got stripped out from the output and I believe this is what is messing with the HTTP API and we stopped sending the one with `path=''`.

**Comment by hsanjuan** [comment]
Thanks for noticing this! This should fix this: https://github.com/ipfs/ipfs-cluster/pull/984

As far as I can see, the added hashes are the same, and this is just a label issue. This was introduced when we aligned the adder with the newer versions in IPFS. Apparently tests don't fail because it adds with `-q` flag and only cids are printed (todo: change that).
